spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/rythulink_ai
spring.datasource.username=root
spring.datasource.password=Poola023!

server.port=8085

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.security.user.name=admin
spring.security.user.password=admin

# Tells Hibernate to create/update tables automatically
spring.jpa.hibernate.ddl-auto=update

# Shows the SQL "CREATE TABLE" commands in your terminal
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Ensure it uses the correct MySQL engine
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

openweather.api.key=0c0c95c16a807fcb1c8b9e893b8389c8
weather.api.key=${OPENWEATHER_API_KEY}

